//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDOANVIENEntities : DbContext
    {
        public QLDOANVIENEntities()
            : base("name=QLDOANVIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_CHIBO> tb_CHIBO { get; set; }
        public virtual DbSet<tb_CHUCVU> tb_CHUCVU { get; set; }
        public virtual DbSet<tb_DANTOC> tb_DANTOC { get; set; }
        public virtual DbSet<tb_DOANVIEN> tb_DOANVIEN { get; set; }
        public virtual DbSet<tb_KHENTHUONG_KYLUAT> tb_KHENTHUONG_KYLUAT { get; set; }
        public virtual DbSet<tb_LOP> tb_LOP { get; set; }
        public virtual DbSet<tb_NOISINHHOATDOAN> tb_NOISINHHOATDOAN { get; set; }
        public virtual DbSet<tb_QUYEN> tb_QUYEN { get; set; }
        public virtual DbSet<tb_TAIKHOAN> tb_TAIKHOAN { get; set; }
        public virtual DbSet<tb_TONGIAO> tb_TONGIAO { get; set; }
        public virtual DbSet<tb_TRINHDO> tb_TRINHDO { get; set; }
        public virtual DbSet<tb_DOANVIEN_BIKHAITRU> tb_DOANVIEN_BIKHAITRU { get; set; }
    }
}
