//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DOANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DOANVIEN()
        {
            this.tb_KHENTHUONG_KYLUAT = new HashSet<tb_KHENTHUONG_KYLUAT>();
        }
    
        public int MADOANVIEN { get; set; }
        public string HOTEN { get; set; }
        public Nullable<bool> GIOITINH { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIENTHOAI { get; set; }
        public string CCCD { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAYVAODOAN { get; set; }
        public Nullable<System.DateTime> NGAYVAODANG { get; set; }
        public string PHIDOAN { get; set; }
        public byte[] HINHANH { get; set; }
        public Nullable<int> IDCHIBO { get; set; }
        public Nullable<int> IDLOP { get; set; }
        public Nullable<int> IDCHUCVU { get; set; }
        public Nullable<int> IDTRINHDO { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
        public Nullable<int> IDTONGIAO { get; set; }
        public Nullable<int> IDDANTOC { get; set; }
        public Nullable<int> MANOISINHHOATDOAN { get; set; }
        public Nullable<bool> DAKHAITRU { get; set; }
    
        public virtual tb_CHIBO tb_CHIBO { get; set; }
        public virtual tb_CHUCVU tb_CHUCVU { get; set; }
        public virtual tb_DANTOC tb_DANTOC { get; set; }
        public virtual tb_LOP tb_LOP { get; set; }
        public virtual tb_NOISINHHOATDOAN tb_NOISINHHOATDOAN { get; set; }
        public virtual tb_TONGIAO tb_TONGIAO { get; set; }
        public virtual tb_TRINHDO tb_TRINHDO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KHENTHUONG_KYLUAT> tb_KHENTHUONG_KYLUAT { get; set; }
    }
}
