//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TAIKHOAN
    {
        public int IDTAILHOAN { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
        public Nullable<int> IDQUYEN { get; set; }
    
        public virtual tb_QUYEN tb_QUYEN { get; set; }
    }
}
